### ISSUE TITLE
Some error ? 

### ISSUE THREAD

**Issue by m7mdcc** [silktide/wappalyzer-wrapper#7]
Hello , thanks for effort .. 

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Silktide\WappalyzerWrapper\Result\TechnologyResult::setName() must be of the type string, null given, called in /var/www/html/example/vendor/silktide/wappalyzer-wrapper/src/Result/ResultProcessor.php on line 63 and defined in /var/www/html/example/vendor/silktide/wappalyzer-wrapper/src/Result/TechnologyResult.php:48

**Comment by andywaite** [comment]
Can you tell us a bit more about the circumstances you got this error?

**Comment by m7mdcc** [comment]
I’m using same example that you have on read me

Thanks

**Comment by andywaite** [comment]
This should now be resolved with release 0.2.6
